### ISSUE TITLE
Getting below error while updating

### ISSUE THREAD

**Issue by prakash02** [abhinavbom/Threat-Intelligence-Hunter#12]
blackhat@ubuntu:~/Downloads/Threat-Intelligence-Hunter-master$ python tih.py -update
 Threat Intelligence Hunter framework Begins now 
Intel test
updating
Traceback (most recent call last):
  File "tih.py", line 62, in <module>
    main()
  File "tih.py", line 59, in main
    gather()
  File "/home/blackhat/Downloads/Threat-Intelligence-Hunter-master/lib/updatefeed.py", line 14, in gather
    os.chdir('.\\intel')
OSError: [Errno 2] No such file or directory: '.\\intel'

**Comment by n0tty** [comment]
The resolution of this error is quite simple.
Edit /lib/updatefeed.py
change `os.chdir('.\\intel')` to `os.chdir('./intel')`
