### ISSUE TITLE
parse.py, parse_ip, NoneType

### ISSUE THREAD

**Issue by trietptm** [abhinavbom/Threat-Intelligence-Hunter#13]
I use Threat-Intelligence-Hunter in a network which blocks Tor and its related websites and received this error:

```
Connecting with https://check.torproject.org/exit-addresses
[!] Could not connect to: https://check.torproject.org/exit-addresses
Traceback (most recent call last):
  File "tih.py", line 62, in <module>
    main()
  File "tih.py", line 41, in main
    parse_ip(args.ip)
  File "c:\GitHub\Threat-Intelligence-Hunter\lib\parse.py", line 75, in parse_ip
    for line in c:
TypeError: 'NoneType' object is not iterable
```

**Comment by abhinavbom** [comment]
you can resolve this issue by commenting out line number 53 in feeds.py
https://github.com/abhinavbom/Threat-Intelligence-Hunter/blob/master/lib/feeds.py#L53
This will avoid connecting to tor network.
