### ISSUE TITLE
Parsing error when running tih.py

### ISSUE THREAD

**Issue by abhinavbom** [abhinavbom/Threat-Intelligence-Hunter#4]
Following parsing error was seen while running the script 

```
Checking Nothink.org SSH bruteforce IPs 
Checking Dragon Research Group VNC probe IP feed 
Traceback (most recent call last):
  File "/Threat-Intelligence-Hunter-master/tih.py", line 29, in <module>
Checking CI Army IP feed 
    main()
  File "/Threat-Intelligence-Hunter-master/tih.py", line 22, in main
    ip_ioc = parse_ip(args.ip)
  File "\Threat-Intelligence-Hunter-master\bin\parse.py", line 45, in parse_ip
    for line in r:
TypeError: 'NoneType' object is not iterable
```

**Comment by abhinavbom** [comment]
Possible issue with CI Army IP feed

**Comment by abhinavbom** [comment]
54a49bb fixes the issue.
